[package]
name = "lambda-http-ric"
version = "0.1.0"
authors = ["Harold Sun <sunhua@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
tokio = { version = "1.4", features = ["macros", "io-util", "sync", "rt-multi-thread", "process"] }
tokio-retry = "0.3"
lambda_http = "0.3.0"
reqwest = { version = "0.11", features = ["json"] }
http = "0.2.4"
openssl-sys = "0.9.61"
nix = "0.22.0"
once_cell = "1.7.2"
futures = "0.3.16"
signal-hook = "0.3.9"
signal-hook-tokio = { version = "0.3.0", features = ["futures-v0_3"] }

[features]
# Force openssl-sys to staticly link in the openssl library. Necessary when
# cross compiling to x86_64-unknown-linux-musl.
vendored = ["openssl-sys/vendored"]

[[bin]]
name = "bootstrap"
path = "src/main.rs"