[package]
name = "aws-lambda-adapter"
version = "0.3.2"
authors = ["Harold Sun <sunhua@amazon.com>"]
edition = "2021"

[dependencies]
env_logger = "0.8.3"
http = "0.2.4"
lambda-extension = "0.5.0"
lambda_http = {git = "https://github.com/bnusunny/aws-lambda-rust-runtime", branch = "main"}
log = "0.4.14"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json"] }
tokio = { version = "1.0", features = ["macros", "io-util", "sync", "rt-multi-thread"] }
tokio-retry = "0.3"

[[bin]]
name = "lambda-adapter"
path = "src/main.rs"

[profile.release]
strip = true
