[package]
name = "lambda-http-ric"
version = "0.1.0"
authors = ["Harold Sun <sunhua@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
tokio = { version = "1.4", features = ["macros", "io-util", "sync", "rt-multi-thread", "process"] }
tokio-retry = "0.3"
lambda_http = "0.3.0"
reqwest = { version = "0.11", features = ["json"] }
