[package]
name = "aws-lambda-adapter"
version = "0.1.2"
authors = ["Harold Sun <sunhua@amazon.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
tokio = { version = "1.4", features = ["macros", "io-util", "sync", "rt-multi-thread", "process"] }
tokio-retry = "0.3"
lambda_http = {git = "https://github.com/bnusunny/aws-lambda-rust-runtime", branch = "extensions"}
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json"] }
http = "0.2.4"
once_cell = "1.7.2"
futures = "0.3.16"
url = "2.1.1"
serde_json = "1.0"

[[bin]]
name = "lambda-adapter"
path = "src/main.rs"
